version: "3"
services:
    frontend:
      image: lakshaycode19/aryavart-frontend:latest
      ports:
        - "3000:3000"
      networks: 
        - new-net


    backend:
      image: lakshaycode19/aryavart-backend:latest
      ports:
        - "8000:8000"
      environment:
        DB_HOST: sql
      depends_on:
        - sql

      networks:
        - new-net

    sql:
      image: postgres:latest
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: leon
        POSTGRES_DB: user_info

      networks:
        - new-net

      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        retries: 5
        start_period: 30s
        timeout: 5s 

      volumes:
        - sqldata:/home/ubuntu/volumes/sql


volumes:
  sqldata: 

networks:
  new-net:

